baseURL = '"https://liaochengxin.github.io/liaochengxin.io/"'
languageCode = 'en-us'
title = 'Chengxin Liao'
theme = "LoveIt"


# whether to include Chinese/Japanese/Korean
# 是否包括中日韩文字
hasCJKLanguage = false


# copyright description used only for seo schema
# 版权描述，仅仅用于 SEO
copyright = ""

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = true
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

# ignore some build errors
# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Pagination config
# 分页配置
[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

# Menu config
# 菜单配置
[menu]
  [[menu.main]]
    weight = 1
    identifier = "home"
    name = "Home"
    url = "/"
    pre = "<i class='fas fa-home fa-fw' aria-hidden='true'></i>"
  [[menu.main]]
    weight = 2
    identifier = "about"
    name = "About"
    url = "/about/"
    pre = "<i class='fas fa-user fa-fw' aria-hidden='true'></i>"
  [[menu.main]]
    weight = 3
    identifier = "Article"
    name = "Article"
    url = "/Article/"
    pre = "<i class='fas fa-file-alt fa-fw' aria-hidden='true'></i>"
  [[menu.main]]
    weight = 4
    identifier = "Note"
    name = "Note"
    url = "/Note/"
    pre = "<i class='fas fa-sticky-note fa-fw' aria-hidden='true'></i>"

[params]
  # site default theme ["auto", "light", "dark"]
  # 网站默认主题 ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/dillonzq/LoveIt"
    # which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  # 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # date format
  # 日期格式
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  # 网站标题, 用于 Open Graph 和 Twitter Cards
  title = "LoveIt"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  # 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
  description = "Chengxin's Academic Website"
  # website images for Open Graph and Twitter Cards
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/header/mynamelogo-removebg-preview.png"]

  #Author config
  #作者配置
  [params.author]
    name = "Chengxin Liao"
    email = "liaocx@ihep.ac.cn"
    #link = "https://your-institution.edu/your-page"
  #Header config
  # 页面头部导航栏配置
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"

  # Header title config
  # 页面头部导航栏标题配置
  [params.header.title]
    #URL of the LOGO
    logo = "/header/mynamelogo-removebg-preview.png"
    #title name
    name = ""
    # you can add extra information before the name (HTML format is supported), such as icons
    #pre = "<i class='far fa-kiss-wink-heart fa-fw' aria-hidden='true'></i>"
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # whether to use typeit animation for title name
    #typeit = false 

  # Footer config
  [params.footer]
    enable = true
    # 可以添加机构信息
    #custom = "Department of Your Department, Your University"
    # whether to show Hugo and theme info
    hugo = true
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # site creation time
    since = 2025
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Section (all post) page config 
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
  # List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
  #App icon config
  [params.app] 
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "LoveIt"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-11 tile color
    tileColor = "#da532c"
  #  Search config
  [params.search]
    enable = true
    # type of search engine ["lunr", "algolia"]
    type = "algolia"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # max number of results length
    maxResultLength = 10
    # snippet length of the result
    snippetLength = 30
    # HTML tag name of the highlight part in results
    highlightTag = "em"
    # whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
  # Home page config
  [params.home] 
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/home/IMG_5229.JPG"
      # title shown in home page (HTML format is supported)
      title = ""
      #titleTypeit = true
      # subtitle shown in home page (HTML format is supported)
      subtitle = "Hi, Welcome to Chengxin's Homepage"
      # whether to use typeit animation for subtitle
      typeit = true  # 关闭副标题的打字机效果
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = "" 

  # Social config in home page
  [params.social]
    GitHub = "https://github.com/Liaochengxin?tab=repositories"
    Linkedin = "https://www.linkedin.com/in/chengxin-liao-14b3a2260/"
    Gitlab = "https://gitlab.cern.ch/liaoc"
    Zhihu = "https://www.zhihu.com/people/liao-51-92"
    Email = "liaocx@ihep.ac.cn" 

  # Page global config
  [params.page]
    # whether to hide a page from home page
    hiddenFromHomePage = false
    # whether to hide a page from search results
    hiddenFromSearch = false
    # whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    # whether to enable the ruby extended syntax
    ruby = true
    # whether to enable the fraction extended syntax
    fraction = true
    # whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # whether to show the full text content in RSS
    rssFullText = false
    # Table of the contents config
  [params.page.math]
    enable = true
  [params.page.code]
    copy = true
  #[params.page.library]
  #  [params.page.library.css]
  #    custom = "css/custom.css"
  [params.assets]
    customCSS = ["css/custom.css"]


[params.typeit]
  # typing speed between each step (measured in milliseconds)
  speed = 100
  # blinking speed of the cursor (measured in milliseconds)
  cursorSpeed = 1000
  # character used for the cursor (HTML format is supported)
  cursorChar = "|"
  # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
  duration = -1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
